name: my_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - cachecontrol==0.14.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cryptography==43.0.1
      - dnspython==2.6.1
      - email-validator==2.2.0
      - exceptiongroup==1.2.2
      - fastapi==0.114.0
      - fastapi-cli==0.0.5
      - filelock==3.16.0
      - firebase-admin==6.5.0
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - google-api-core==2.19.2
      - google-api-python-client==2.145.0
      - google-auth==2.34.0
      - google-auth-httplib2==0.2.0
      - google-cloud-core==2.4.1
      - google-cloud-firestore==2.18.0
      - google-cloud-storage==2.18.2
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.65.0
      - grpcio==1.66.1
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.2
      - idna==3.8
      - itsdangerous==2.2.0
      - kiwipiepy==0.18.1
      - kiwipiepy-model==0.18.0
      - msgpack==1.1.0
      - numpy==1.26.4
      - pdfminer-six==20231228
      - pdfplumber==0.11.4
      - pillow==10.4.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.9.1
      - pydantic-core==2.23.3
      - pyjwt==2.9.0
      - pyparsing==3.1.4
      - pypdfium2==4.30.0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - requests==2.32.3
      - rsa==4.9
      - sniffio==1.3.1
      - soupsieve==2.6
      - starlette==0.38.5
      - sympy==1.13.1
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tinydb==4.8.0
      - tokenizers==0.19.1
      - torch==2.4.0
      - tqdm==4.66.5
      - typing-extensions==4.12.2
      - uritemplate==4.1.1
      - urllib3==2.2.2
      - uvicorn==0.30.6
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - yarl==1.9.7